name: Convert FreeCAD to STL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install FreeCAD
      run: |
        sudo add-apt-repository --yes ppa:freecad-maintainers/freecad-stable
        sudo apt-get update
        sudo apt-get install -y freecad freecad-python3

    - name: Create conversion script
      run: |
        echo "import FreeCAD" > convert_to_stl.py
        echo "import Mesh" >> convert_to_stl.py
        echo "doc = FreeCAD.open('model/test.FCStd')" >> convert_to_stl.py
        echo "print('Objects in the document:')" >> convert_to_stl.py
        echo "for obj in doc.Objects:" >> convert_to_stl.py
        echo "    print(obj.Name)" >> convert_to_stl.py
        echo "obj = doc.getObject('Body')" >> convert_to_stl.py
        echo "if obj is not None:" >> convert_to_stl.py
        echo "    Mesh.export([obj], 'model/Pacman.stl')" >> convert_to_stl.py
        echo "else:" >> convert_to_stl.py
        echo "    print('Object Body not found')" >> convert_to_stl.py
        echo "doc.close()" >> convert_to_stl.py

    - name: Convert FCStd to STL
      run: |
        freecadcmd convert_to_stl.py

    - name: List generated STL files
      run: |
        ls -l model/*.stl

    - name: Upload STL files
      uses: actions/upload-artifact@v3
      with:
        name: stl-files
        path: model/*.stl

    - name: Configure git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit STL file
      run: |
        git add model/Pacman.stl
        git commit -m "Update Pacman.stl"

    - name: Push changes
      run: |
        git push origin HEAD:main

    - name: Clean up
      run: |
        rm convert_to_stl.py
